[theme]
base="dark"
primaryColor="#FF9800"                # warm orange for buttons/sliders
backgroundColor="#0E1117"             # deep dark background
secondaryBackgroundColor="#262730"    # for sidebars and containers
textColor="#FAFAFA"                   # light text
font="sans serif"
